### ISSUE TITLE
Debian 11: "stream is not active"

### ISSUE THREAD

**Issue by philcryer** [jonahsnider/mandolin-rip#52]
Hey, this is a great project, and I have the ability to re-watch a show I'd like to save, I followed your directions, setup the API key where it should be, and everything went fine until I ran `yarn start` when I get an error "stream is not active". I've tried this many times with new API keys/tokens, but it hasn't worked. If you have any ideas on how to fix, I'd love to get it working! Thanks

Debian 11
Node v19.3.0
npm 9.2.0
yarn 3.1.1

```
phil@slim:~/mandolin-rip$ yarn start
ℹ starting thread                                                                                                       4061d9ba-8f61-400b-8887-93b7b2be612c:thread-0 19:55:52
ℹ starting thread                                                                                                       fb967cfb-9a9c-436a-8c27-1a9c23f20a22:thread-1 19:55:52
ℹ starting thread                                                                                                       d8cd5355-7bf4-480c-abc2-64d95f18296a:thread-2 19:55:52
ℹ starting thread                                                                                                       7f8e1ec8-ec05-4077-937a-dfc9349d19c3:thread-3 19:55:52

 WARN  stream is not active                                                                                             4061d9ba-8f61-400b-8887-93b7b2be612c:thread-0 19:55:53

 WARN  stream is not active                                                                                             fb967cfb-9a9c-436a-8c27-1a9c23f20a22:thread-1 19:55:53

 WARN  stream is not active                                                                                             d8cd5355-7bf4-480c-abc2-64d95f18296a:thread-2 19:55:53

 WARN  stream is not active                                                                                             7f8e1ec8-ec05-4077-937a-dfc9349d19c3:thread-3 19:55:53

 ERROR  Response code 412 (Precondition Failed)                                                                         7f8e1ec8-ec05-4077-937a-dfc9349d19c3:thread-3 19:55:53

  at Request.<anonymous> (node_modules/got/dist/source/as-promise/index.js:117:42)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Response code 412 (Precondition Failed)                                                                         4061d9ba-8f61-400b-8887-93b7b2be612c:thread-0 19:55:53

  at Request.<anonymous> (node_modules/got/dist/source/as-promise/index.js:117:42)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


 ERROR  Response code 412 (Precondition Failed)                                                                         fb967cfb-9a9c-436a-8c27-1a9c23f20a22:thread-1 19:55:53

  at Request.<anonymous> (node_modules/got/dist/source/as-promise/index.js:117:42)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 ERROR  Response code 412 (Precondition Failed)                                                                         d8cd5355-7bf4-480c-abc2-64d95f18296a:thread-2 19:55:53

  at Request.<anonymous> (node_modules/got/dist/source/as-promise/index.js:117:42)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jonahsnider** [comment]
Unfortunately the tool only supports downloading streams as they occur live, it's not compatible with the recorded versions.
